import mammoth from 'mammoth';
import * as CFB from 'cfb';
import { SectionItem } from '../types';
import { estimateAudioDuration } from './fileParsers';

export interface WordParseResult {
  title: string;
  totalWords: number;
  sections: SectionItem[];
  fileType: 'docx' | 'doc';
  pageCount?: number;
}

/**
 * Extracts plain text and structured headings from an HTML string generated by mammoth
 */
function parseHtmlSections(htmlString: string, defaultTitle: string): { sections: SectionItem[]; totalWords: number } {
  const parser = new DOMParser();
  const doc = parser.parseFromString(htmlString, 'text/html');

  const elements = Array.from(doc.body.children);
  const sections: SectionItem[] = [];
  let totalWordCount = 0;

  let currentHeading = 'Opening Section';
  let currentParagraphs: string[] = [];

  const flushSection = () => {
    if (currentParagraphs.length === 0) return;
    const combinedText = currentParagraphs.join('\n\n').trim();
    if (!combinedText) return;

    const words = combinedText.split(/\s+/).filter(Boolean);
    if (words.length > 0) {
      totalWordCount += words.length;
      const sectionIndex = sections.length;
      sections.push({
        id: `word_sec_${sectionIndex}_${Date.now()}`,
        pageNumber: Math.floor(sectionIndex / 3) + 1,
        title: currentHeading,
        text: combinedText,
        wordCount: words.length,
      });
    }
    currentParagraphs = [];
  };

  for (const el of elements) {
    const tagName = el.tagName.toLowerCase();
    const textContent = (el.textContent || '').trim();
    if (!textContent) continue;

    // Check if element is a heading (h1, h2, h3, h4, h5, h6)
    if (/^h[1-6]$/.test(tagName)) {
      flushSection();
      currentHeading = textContent;
    } else {
      // Regular paragraph, list item, blockquote, or table row
      currentParagraphs.push(textContent);
      // If the section is getting long (e.g. over 300 words), split into comfortable listening parts
      const currentWords = currentParagraphs.join(' ').split(/\s+/).length;
      if (currentWords > 350) {
        flushSection();
      }
    }
  }

  // Flush remaining paragraphs
  flushSection();

  // If no sections were built (e.g. text wasn't in children), fallback to raw text
  if (sections.length === 0) {
    const raw = (doc.body.textContent || '').trim();
    if (raw) {
      const paragraphs = raw.split(/\n{2,}/).map((p) => p.trim()).filter(Boolean);
      paragraphs.forEach((p, idx) => {
        const words = p.split(/\s+/).filter(Boolean);
        if (words.length > 0) {
          totalWordCount += words.length;
          sections.push({
            id: `word_sec_${idx}_${Date.now()}`,
            pageNumber: Math.floor(idx / 3) + 1,
            title: `${defaultTitle} (Part ${idx + 1})`,
            text: p,
            wordCount: words.length,
          });
        }
      });
    }
  }

  return { sections, totalWords: totalWordCount };
}

/**
 * Extracts readable strings from binary buffer of older Word 97-2003 (.doc) files
 */
function extractTextFromBinaryDoc(arrayBuffer: ArrayBuffer, title: string): { sections: SectionItem[]; totalWords: number } {
  const bytes = new Uint8Array(arrayBuffer);

  // 1. Check if the file is actually RTF
  const headerStr = String.fromCharCode(...bytes.slice(0, 10));
  if (headerStr.startsWith('{\\rtf')) {
    const rtfDecoder = new TextDecoder('windows-1252', { fatal: false });
    const rtfText = rtfDecoder.decode(bytes);
    const cleaned = rtfText
      .replace(/\\par[d]?/g, '\n')
      .replace(/\{\\*?\\[^{}]+;?\}|[{}\\]/g, ' ')
      .replace(/\\'([0-9a-fA-F]{2})/g, (_, hex) => String.fromCharCode(parseInt(hex, 16)))
      .replace(/\s+/g, ' ')
      .trim();

    return parsePlainTextToSections(cleaned, title);
  }

  // 2. Try parsing via CFB (Compound File Binary)
  try {
    const cfb = CFB.read(bytes, { type: 'array' });
    const wordDocEntry = CFB.find(cfb, '/WordDocument') || cfb.FileIndex.find((e) => e.name.toLowerCase() === 'worddocument');

    if (wordDocEntry && wordDocEntry.content) {
      const streamBytes = new Uint8Array(wordDocEntry.content as number[]);
      const extractedText = extractPrintableRuns(streamBytes);
      if (extractedText.length > 30) {
        return parsePlainTextToSections(extractedText, title);
      }
    }
  } catch (cfbErr) {
    console.warn('CFB parsing failed for .doc file, using binary string scanner', cfbErr);
  }

  // 3. Fallback: Scan full binary array for printable UTF-16LE and ASCII sequences
  const rawExtracted = extractPrintableRuns(bytes);
  return parsePlainTextToSections(rawExtracted, title);
}

/**
 * Extracts coherent readable text blocks from binary streams
 */
function extractPrintableRuns(bytes: Uint8Array): string {
  // Try UTF-16LE decoder
  const utf16Decoder = new TextDecoder('utf-16le', { fatal: false });
  const utf16Text = utf16Decoder.decode(bytes);

  // Filter sequences of printable unicode/ASCII text (min 4 words)
  const utf16Clean = utf16Text
    .replace(/[\x00-\x08\x0B\x0C\x0E-\x1F\x7F-\x9F]/g, ' ')
    .replace(/[^\P{C}\n\r\t]/u, ' ');

  // Try Windows-1252 / Latin-1 for 8-bit doc files
  const latinDecoder = new TextDecoder('windows-1252', { fatal: false });
  const latinText = latinDecoder.decode(bytes);
  const latinClean = latinText.replace(/[\x00-\x08\x0B\x0C\x0E-\x1F\x7F-\x9F]/g, ' ');

  // Choose whichever yielded more coherent alphanumeric characters
  const utf16Words = utf16Clean.match(/[a-zA-Z0-9]{2,}/g) || [];
  const latinWords = latinClean.match(/[a-zA-Z0-9]{2,}/g) || [];

  const candidate = utf16Words.length >= latinWords.length ? utf16Clean : latinClean;

  // Group into paragraphs by keeping sentences with standard punctuation
  const lines = candidate
    .split(/[\r\n]+/)
    .map((l) => l.replace(/\s+/g, ' ').trim())
    .filter((l) => {
      // Must have at least 3 readable words and not look like binary garbage
      const words = l.split(' ').filter((w) => /^[a-zA-Z0-9.,'"?!;:()\-—]+$/.test(w));
      return words.length >= 3 && l.length > 15;
    });

  return lines.join('\n\n');
}

/**
 * Converts plain text into structured section items
 */
function parsePlainTextToSections(rawText: string, title: string): { sections: SectionItem[]; totalWords: number } {
  const paragraphs = rawText
    .split(/\n{2,}/)
    .map((p) => p.trim())
    .filter((p) => p.length > 0);

  const sections: SectionItem[] = [];
  let totalWordCount = 0;

  paragraphs.forEach((p, idx) => {
    const words = p.split(/\s+/).filter(Boolean);
    if (words.length > 0) {
      totalWordCount += words.length;
      sections.push({
        id: `doc_sec_${idx}_${Date.now()}`,
        pageNumber: Math.floor(idx / 3) + 1,
        title: `Section ${idx + 1}`,
        text: p,
        wordCount: words.length,
      });
    }
  });

  if (sections.length === 0) {
    sections.push({
      id: `doc_empty_${Date.now()}`,
      title: 'Empty Document',
      text: 'No readable text could be found in this Word file.',
      wordCount: 10,
    });
    totalWordCount = 10;
  }

  return { sections, totalWords: totalWordCount };
}

/**
 * Main parser for Word documents (.docx and .doc), completely offline in the browser
 */
export async function parseWordFile(
  file: File,
  onProgress?: (status: string) => void
): Promise<WordParseResult> {
  const extension = file.name.split('.').pop()?.toLowerCase() || 'docx';
  const cleanTitle = file.name.replace(/\.[^/.]+$/, '').replace(/[_+-]+/g, ' ');
  const arrayBuffer = await file.arrayBuffer();

  if (onProgress) {
    onProgress('Reading Word document contents...');
  }

  // First try: Mammoth (perfect for .docx)
  try {
    const result = await mammoth.convertToHtml({ arrayBuffer });
    const { sections, totalWords } = parseHtmlSections(result.value, cleanTitle);

    if (sections.length > 0 && totalWords > 0) {
      return {
        title: cleanTitle,
        totalWords,
        sections,
        fileType: extension === 'doc' ? 'doc' : 'docx',
        pageCount: Math.ceil(totalWords / 250),
      };
    }
  } catch (docxErr) {
    console.warn('Mammoth conversion was not applicable (likely legacy .doc format):', docxErr);
  }

  // Second try: Older Word binary format (.doc) or RTF
  if (onProgress) {
    onProgress('Extracting text from legacy Word document (.doc)...');
  }

  const { sections, totalWords } = extractTextFromBinaryDoc(arrayBuffer, cleanTitle);

  return {
    title: cleanTitle,
    totalWords,
    sections,
    fileType: extension === 'doc' ? 'doc' : 'docx',
    pageCount: Math.ceil(totalWords / 250),
  };
}
